export const currencyOptionsData = [
    { value: "AFN", label: "AFN - Afghan Afghani - ؋", img: "/images/flags/1x1/af.svg" },
    { value: "ALL", label: "ALL - Albanian Lek - Lek", img: "/images/flags/1x1/al.svg" },
    { value: "DZD", label: "DZD - Algerian Dinar - دج", img: "/images/flags/1x1/dz.svg" },
    { value: "AOA", label: "AOA - Angolan Kwanza - Kz", img: "/images/flags/1x1/ao.svg" },
    { value: "ARS", label: "ARS - Argentine Peso - $", img: "/images/flags/1x1/ar.svg" },
    { value: "AMD", label: "AMD - Armenian Dram - ֏", img: "/images/flags/1x1/am.svg" },
    { value: "AWG", label: "AWG - Aruban Florin - ƒ", img: "/images/flags/1x1/aw.svg" },
    { value: "AUD", label: "AUD - Australian Dollar - $", img: "/images/flags/1x1/au.svg" },
    { value: "AZN", label: "AZN - Azerbaijani Manat - m", img: "/images/flags/1x1/az.svg" },
    { value: "BSD", label: "BSD - Bahamian Dollar - B$", img: "/images/flags/1x1/bs.svg" },
    { value: "BHD", label: "BHD - Bahraini Dinar - .د.ب", img: "/images/flags/1x1/bh.svg" },
    { value: "BDT", label: "BDT - Bangladeshi Taka - ৳", img: "/images/flags/1x1/bd.svg" },
    { value: "BBD", label: "BBD - Barbadian Dollar - Bds$", img: "/images/flags/1x1/bb.svg" },
    { value: "BYR", label: "BYR - Belarusian Ruble - Br", img: "/images/flags/1x1/by.svg" },
    { value: "BEF", label: "BEF - Belgian Franc - fr", img: "/images/flags/1x1/be.svg" },
    { value: "BZD", label: "BZD - Belize Dollar - $", img: "/images/flags/1x1/bz.svg" },
    { value: "BMD", label: "BMD - Bermudan Dollar - $", img: "/images/flags/1x1/bm.svg" },
    { value: "BTN", label: "BTN - Bhutanese Ngultrum - Nu.", img: "/images/flags/1x1/bt.svg" },
    { value: "BTC", label: "BTC - Bitcoin - ฿", img: "/images/flags/1x1/btc.svg" }, // Bitcoin doesn't have a country flag
    { value: "BOB", label: "BOB - Bolivian Boliviano - Bs.", img: "/images/flags/1x1/bo.svg" },
    { value: "BAM", label: "BAM - Bosnia-Herzegovina Convertible Mark - KM", img: "/images/flags/1x1/ba.svg" },
    { value: "BWP", label: "BWP - Botswanan Pula - P", img: "/images/flags/1x1/bw.svg" },
    { value: "BRL", label: "BRL - Brazilian Real - R$", img: "/images/flags/1x1/br.svg" },
    { value: "GBP", label: "GBP - British Pound Sterling - £", img: "/images/flags/1x1/gb.svg" },
    { value: "BND", label: "BND - Brunei Dollar - B$", img: "/images/flags/1x1/bn.svg" },
    { value: "BGN", label: "BGN - Bulgarian Lev - Лв.", img: "/images/flags/1x1/bg.svg" },
    { value: "BIF", label: "BIF - Burundian Franc - FBu", img: "/images/flags/1x1/bi.svg" },
    { value: "KHR", label: "KHR - Cambodian Riel - KHR", img: "/images/flags/1x1/kh.svg" },
    { value: "CAD", label: "CAD - Canadian Dollar - $", img: "/images/flags/1x1/ca.svg" },
    { value: "CVE", label: "CVE - Cape Verdean Escudo - $", img: "/images/flags/1x1/cv.svg" },
    { value: "KYD", label: "KYD - Cayman Islands Dollar - $", img: "/images/flags/1x1/ky.svg" },
    { value: "XOF", label: "XOF - CFA Franc BCEAO - CFA", img: "/images/flags/1x1/fr.svg" }, // Used in multiple countries
    { value: "XAF", label: "XAF - CFA Franc BEAC - FCFA", img: "/images/flags/1x1/fr.svg" }, // Used in multiple countries
    { value: "XPF", label: "XPF - CFP Franc - ₣", img: "/images/flags/1x1/fr.svg" }, // Used in multiple territories
    { value: "CLP", label: "CLP - Chilean Peso - $", img: "/images/flags/1x1/cl.svg" },
    { value: "CNY", label: "CNY - Chinese Yuan - ¥", img: "/images/flags/1x1/cn.svg" },
    { value: "COP", label: "COP - Colombian Peso - $", img: "/images/flags/1x1/co.svg" },
    { value: "KMF", label: "KMF - Comorian Franc - CF", img: "/images/flags/1x1/km.svg" },
    { value: "CDF", label: "CDF - Congolese Franc - FC", img: "/images/flags/1x1/cd.svg" },
    { value: "CRC", label: "CRC - Costa Rican Colón - ₡", img: "/images/flags/1x1/cr.svg" },
    { value: "HRK", label: "HRK - Croatian Kuna - kn", img: "/images/flags/1x1/hr.svg" },
    { value: "CUC", label: "CUC - Cuban Convertible Peso - $, CUC", img: "/images/flags/1x1/cu.svg" },
    { value: "CZK", label: "CZK - Czech Republic Koruna - Kč", img: "/images/flags/1x1/cz.svg" },
    { value: "DKK", label: "DKK - Danish Krone - Kr.", img: "/images/flags/1x1/dk.svg" },
    { value: "DJF", label: "DJF - Djiboutian Franc - Fdj", img: "/images/flags/1x1/dj.svg" },
    { value: "DOP", label: "DOP - Dominican Peso - $", img: "/images/flags/1x1/do.svg" },
    { value: "XCD", label: "XCD - East Caribbean Dollar - $", img: "/images/flags/1x1/bq.svg" }, // Used in multiple countries
    { value: "EGP", label: "EGP - Egyptian Pound - ج.م", img: "/images/flags/1x1/eg.svg" },
    { value: "ERN", label: "ERN - Eritrean Nakfa - Nfk", img: "/images/flags/1x1/er.svg" },
    { value: "EEK", label: "EEK - Estonian Kroon - kr", img: "/images/flags/1x1/ee.svg" },
    { value: "ETB", label: "ETB - Ethiopian Birr - Nkf", img: "/images/flags/1x1/et.svg" },
    { value: "EUR", label: "EUR - Euro - €", img: "/images/flags/1x1/eu.svg" }, // Used in multiple countries
    { value: "FKP", label: "FKP - Falkland Islands Pound - £", img: "/images/flags/1x1/fk.svg" },
    { value: "FJD", label: "FJD - Fijian Dollar - FJ$", img: "/images/flags/1x1/fj.svg" },
    { value: "GMD", label: "GMD - Gambian Dalasi - D", img: "/images/flags/1x1/gm.svg" },
    { value: "GEL", label: "GEL - Georgian Lari - ლ", img: "/images/flags/1x1/ge.svg" },
    { value: "DEM", label: "DEM - German Mark - DM", img: "/images/flags/1x1/de.svg" },
    { value: "GHS", label: "GHS - Ghanaian Cedi - GH₵", img: "/images/flags/1x1/gh.svg" },
    { value: "GIP", label: "GIP - Gibraltar Pound - £", img: "/images/flags/1x1/gi.svg" },
    { value: "GRD", label: "GRD - Greek Drachma - ₯, Δρχ, Δρ", img: "/images/flags/1x1/gr.svg" },
    { value: "GTQ", label: "GTQ - Guatemalan Quetzal - Q", img: "/images/flags/1x1/gt.svg" },
    { value: "GNF", label: "GNF - Guinean Franc - FG", img: "/images/flags/1x1/gn.svg" },
    { value: "GYD", label: "GYD - Guyanaese Dollar - $", img: "/images/flags/1x1/gy.svg" },
    { value: "HTG", label: "HTG - Haitian Gourde - G", img: "/images/flags/1x1/ht.svg" },
    { value: "HNL", label: "HNL - Honduran Lempira - L", img: "/images/flags/1x1/hn.svg" },
    { value: "HKD", label: "HKD - Hong Kong Dollar - $", img: "/images/flags/1x1/hk.svg" },
    { value: "HUF", label: "HUF - Hungarian Forint - Ft", img: "/images/flags/1x1/hu.svg" },
    { value: "ISK", label: "ISK - Icelandic Króna - kr", img: "/images/flags/1x1/is.svg" },
    { value: "INR", label: "INR - Indian Rupee - ₹", img: "/images/flags/1x1/in.svg" },
    { value: "IDR", label: "IDR - Indonesian Rupiah - Rp", img: "/images/flags/1x1/id.svg" },
    { value: "IRR", label: "IRR - Iranian Rial - ﷼", img: "/images/flags/1x1/ir.svg" },
    { value: "IQD", label: "IQD - Iraqi Dinar - د.ع", img: "/images/flags/1x1/iq.svg" },
    { value: "ILS", label: "ILS - Israeli New Sheqel - ₪", img: "/images/flags/1x1/il.svg" },
    { value: "ITL", label: "ITL - Italian Lira - L,£", img: "/images/flags/1x1/it.svg" },
    { value: "JMD", label: "JMD - Jamaican Dollar - J$", img: "/images/flags/1x1/jm.svg" },
    { value: "JPY", label: "JPY - Japanese Yen - ¥", img: "/images/flags/1x1/jp.svg" },
    { value: "JOD", label: "JOD - Jordanian Dinar - ا.د", img: "/images/flags/1x1/jo.svg" },
    { value: "KZT", label: "KZT - Kazakhstani Tenge - лв", img: "/images/flags/1x1/kz.svg" },
    { value: "KES", label: "KES - Kenyan Shilling - KSh", img: "/images/flags/1x1/ke.svg" },
    { value: "KWD", label: "KWD - Kuwaiti Dinar - ك.د", img: "/images/flags/1x1/kw.svg" },
    { value: "KGS", label: "KGS - Kyrgystani Som - лв", img: "/images/flags/1x1/kg.svg" },
    { value: "LAK", label: "LAK - Laotian Kip - ₭", img: "/images/flags/1x1/la.svg" },
    { value: "LVL", label: "LVL - Latvian Lats - Ls", img: "/images/flags/1x1/lv.svg" },
    { value: "LBP", label: "LBP - Lebanese Pound - £", img: "/images/flags/1x1/lb.svg" },
    { value: "LSL", label: "LSL - Lesotho Loti - L", img: "/images/flags/1x1/ls.svg" },
    { value: "LRD", label: "LRD - Liberian Dollar - $", img: "/images/flags/1x1/lr.svg" },
    { value: "LYD", label: "LYD - Libyan Dinar - د.ل", img: "/images/flags/1x1/ly.svg" },
    { value: "LTL", label: "LTL - Lithuanian Litas - Lt", img: "/images/flags/1x1/lt.svg" },
    { value: "MOP", label: "MOP - Macanese Pataca - $", img: "/images/flags/1x1/mo.svg" },
    { value: "MKD", label: "MKD - Macedonian Denar - ден", img: "/images/flags/1x1/mk.svg" },
    { value: "MGA", label: "MGA - Malagasy Ariary - Ar", img: "/images/flags/1x1/mg.svg" },
    { value: "MWK", label: "MWK - Malawian Kwacha - MK", img: "/images/flags/1x1/mw.svg" },
    { value: "MYR", label: "MYR - Malaysian Ringgit - RM", img: "/images/flags/1x1/my.svg" },
    { value: "MVR", label: "MVR - Maldivian Rufiyaa - Rf", img: "/images/flags/1x1/mv.svg" },
    { value: "MRO", label: "MRO - Mauritanian Ouguiya - MRU", img: "/images/flags/1x1/mr.svg" },
    { value: "MUR", label: "MUR - Mauritian Rupee - ₨", img: "/images/flags/1x1/mu.svg" },
    { value: "MXN", label: "MXN - Mexican Peso - $", img: "/images/flags/1x1/mx.svg" },
    { value: "MDL", label: "MDL - Moldovan Leu - L", img: "/images/flags/1x1/md.svg" },
    { value: "MNT", label: "MNT - Mongolian Tugrik - ₮", img: "/images/flags/1x1/mn.svg" },
    { value: "MAD", label: "MAD - Moroccan Dirham - MAD", img: "/images/flags/1x1/ma.svg" },
    { value: "MZM", label: "MZM - Mozambican Metical - MT", img: "/images/flags/1x1/mz.svg" },
    { value: "MMK", label: "MMK - Myanmar Kyat - K", img: "/images/flags/1x1/mm.svg" },
    { value: "NAD", label: "NAD - Namibian Dollar - $", img: "/images/flags/1x1/na.svg" },
    { value: "NPR", label: "NPR - Nepalese Rupee - ₨", img: "/images/flags/1x1/np.svg" },
    { value: "ANG", label: "ANG - Netherlands Antillean Guilder - ƒ", img: "/images/flags/1x1/nl.svg" },
    { value: "TWD", label: "TWD - New Taiwan Dollar - $", img: "/images/flags/1x1/tw.svg" },
    { value: "NZD", label: "NZD - New Zealand Dollar - $", img: "/images/flags/1x1/nz.svg" },
    { value: "NIO", label: "NIO - Nicaraguan Córdoba - C$", img: "/images/flags/1x1/ni.svg" },
    { value: "NGN", label: "NGN - Nigerian Naira - ₦", img: "/images/flags/1x1/ng.svg" },
    { value: "KPW", label: "KPW - North Korean Won - ₩", img: "/images/flags/1x1/kp.svg" },
    { value: "NOK", label: "NOK - Norwegian Krone - kr", img: "/images/flags/1x1/no.svg" },
    { value: "OMR", label: "OMR - Omani Rial - .ع.ر", img: "/images/flags/1x1/om.svg" },
    { value: "PKR", label: "PKR - Pakistani Rupee - ₨", img: "/images/flags/1x1/pk.svg" },
    { value: "PAB", label: "PAB - Panamanian Balboa - B/.", img: "/images/flags/1x1/pa.svg" },
    { value: "PGK", label: "PGK - Papua New Guinean Kina - K", img: "/images/flags/1x1/pg.svg" },
    { value: "PYG", label: "PYG - Paraguayan Guarani - ₲", img: "/images/flags/1x1/py.svg" },
    { value: "PEN", label: "PEN - Peruvian Nuevo Sol - S/.", img: "/images/flags/1x1/pe.svg" },
    { value: "PHP", label: "PHP - Philippine Peso - ₱", img: "/images/flags/1x1/ph.svg" },
    { value: "PLN", label: "PLN - Polish Zloty - zł", img: "/images/flags/1x1/pl.svg" },
    { value: "QAR", label: "QAR - Qatari Rial - ق.ر", img: "/images/flags/1x1/qa.svg" },
    { value: "RON", label: "RON - Romanian Leu - lei", img: "/images/flags/1x1/ro.svg" },
    { value: "RUB", label: "RUB - Russian Ruble - ₽", img: "/images/flags/1x1/ru.svg" },
    { value: "RWF", label: "RWF - Rwandan Franc - FRw", img: "/images/flags/1x1/rw.svg" },
    { value: "SVC", label: "SVC - Salvadoran Colón - ₡", img: "/images/flags/1x1/sv.svg" },
    { value: "WST", label: "WST - Samoan Tala - SAT", img: "/images/flags/1x1/ws.svg" },
    { value: "SAR", label: "SAR - Saudi Riyal - ﷼", img: "/images/flags/1x1/sa.svg" },
    { value: "RSD", label: "RSD - Serbian Dinar - din", img: "/images/flags/1x1/sr.svg" },
    { value: "SCR", label: "SCR - Seychellois Rupee - SRe", img: "/images/flags/1x1/sc.svg" },
    { value: "SLL", label: "SLL - Sierra Leonean Leone - Le", img: "/images/flags/1x1/sl.svg" },
    { value: "SGD", label: "SGD - Singapore Dollar - $", img: "/images/flags/1x1/sg.svg" },
    { value: "SKK", label: "SKK - Slovak Koruna - Sk", img: "/images/flags/1x1/sk.svg" },
    { value: "SBD", label: "SBD - Solomon Islands Dollar - Si$", img: "/images/flags/1x1/sb.svg" },
    { value: "SOS", label: "SOS - Somali Shilling - Sh.so.", img: "/images/flags/1x1/so.svg" },
    { value: "ZAR", label: "ZAR - South African Rand - R", img: "/images/flags/1x1/za.svg" },
    { value: "KRW", label: "KRW - South Korean Won - ₩", img: "/images/flags/1x1/kr.svg" },
    { value: "LKR", label: "LKR - Sri Lankan Rupee - Rs", img: "/images/flags/1x1/lk.svg" },
    { value: "SHP", label: "SHP - St. Helena Pound - £", img: "/images/flags/1x1/sh.svg" },
    { value: "SDG", label: "SDG - Sudanese Pound - .س.ج", img: "/images/flags/1x1/sd.svg" },
    { value: "SRD", label: "SRD - Surinamese Dollar - $", img: "/images/flags/1x1/sr.svg" },
    { value: "SZL", label: "SZL - Swazi Lilangeni - E", img: "/images/flags/1x1/sz.svg" },
    { value: "SEK", label: "SEK - Swedish Krona - kr", img: "/images/flags/1x1/se.svg" },
    { value: "CHF", label: "CHF - Swiss Franc - CHf", img: "/images/flags/1x1/ch.svg" },
    { value: "SYP", label: "SYP - Syrian Pound - LS", img: "/images/flags/1x1/sy.svg" },
    { value: "STD", label: "STD - São Tomé and Príncipe Dobra - Db", img: "/images/flags/1x1/st.svg" },
    { value: "TJS", label: "TJS - Tajikistani Somoni - SM", img: "/images/flags/1x1/tj.svg" },
    { value: "TZS", label: "TZS - Tanzanian Shilling - TSh", img: "/images/flags/1x1/tz.svg" },
    { value: "THB", label: "THB - Thai Baht - ฿", img: "/images/flags/1x1/th.svg" },
    { value: "TOP", label: "TOP - Tongan pa'anga - $", img: "/images/flags/1x1/to.svg" },
    { value: "TTD", label: "TTD - Trinidad & Tobago Dollar - $", img: "/images/flags/1x1/tt.svg" },
    { value: "TND", label: "TND - Tunisian Dinar - ت.د", img: "/images/flags/1x1/tn.svg" },
    { value: "TRY", label: "TRY - Turkish Lira - ₺", img: "/images/flags/1x1/tr.svg" },
    { value: "TMT", label: "TMT - Turkmenistani Manat - T", img: "/images/flags/1x1/tm.svg" },
    { value: "UGX", label: "UGX - Ugandan Shilling - USh", img: "/images/flags/1x1/ug.svg" },
    { value: "UAH", label: "UAH - Ukrainian Hryvnia - ₴", img: "/images/flags/1x1/ua.svg" },
    { value: "AED", label: "AED - United Arab Emirates Dirham - إ.د", img: "/images/flags/1x1/ae.svg" },
    { value: "UYU", label: "UYU - Uruguayan Peso - $", img: "/images/flags/1x1/uy.svg" },
    { value: "USD", label: "USD - US Dollar - $", img: "/images/flags/1x1/us.svg" },
    { value: "UZS", label: "UZS - Uzbekistan Som - лв", img: "/images/flags/1x1/uz.svg" },
    { value: "VUV", label: "VUV - Vanuatu Vatu - VT", img: "/images/flags/1x1/vu.svg" },
    { value: "VEF", label: "VEF - Venezuelan Bolívar - Bs", img: "/images/flags/1x1/ve.svg" },
    { value: "VND", label: "VND - Vietnamese Dong - ₫", img: "/images/flags/1x1/vn.svg" },
    { value: "YER", label: "YER - Yemeni Rial - ﷼", img: "/images/flags/1x1/ye.svg" },
    { value: "ZMK", label: "ZMK - Zambian Kwacha - ZK", img: "/images/flags/1x1/zm.svg" }
];

