export const timezonesData = [
    { value: 'Eniwetok', label: '(GMT -12:00) Eniwetok, Kwajalein', icon: 'feather-moon' },
    { value: 'Midway Island', label: '(GMT -11:00) Midway Island, Samoa', icon: 'feather-moon' },
    { value: 'Hawaii', label: '(GMT -10:00) Hawaii', icon: 'feather-moon' },
    { value: 'Taiohae', label: '(GMT -9:30) Taiohae', icon: 'feather-moon' },
    { value: 'Alaska', label: '(GMT -9:00) Alaska', icon: 'feather-moon' },
    { value: 'Pacific Time (US & Canada)', label: '(GMT -8:00) Pacific Time (US & Canada)', icon: 'feather-moon' },
    { value: 'Mountain Time (US & Canada)', label: '(GMT -7:00) Mountain Time (US & Canada)', icon: 'feather-moon' },
    { value: 'Central Time (US & Canada), Mexico City', label: '(GMT -6:00) Central Time (US & Canada), Mexico City', icon: 'feather-moon' },
    { value: 'Eastern Time (US & Canada), Bogota, Lima', label: '(GMT -5:00) Eastern Time (US & Canada), Bogota, Lima', icon: 'feather-moon' },
    { value: 'Caracas', label: '(GMT -4:30) Caracas', icon: 'feather-moon' },
    { value: 'Atlantic Time (Canada), Caracas, La Paz', label: '(GMT -4:00) Atlantic Time (Canada), Caracas, La Paz', icon: 'feather-moon' },
    { value: 'Newfoundland', label: '(GMT -3:30) Newfoundland', icon: 'feather-moon' },
    { value: 'Brazil, Buenos Aires, Georgetown', label: '(GMT -3:00) Brazil, Buenos Aires, Georgetown', icon: 'feather-moon' },
    { value: 'Mid-Atlantic', label: '(GMT -2:00) Mid-Atlantic', icon: 'feather-moon' },
    { value: 'Azores, Cape Verde Islands', label: '(GMT -1:00) Azores, Cape Verde Islands', icon: 'feather-moon' },
    { value: 'Western Europe Time', label: '(GMT) Western Europe Time', icon: 'feather-sunrise' },
    { value: 'Brussels, Copenhagen, Madrid, Paris', label: '(GMT +1:00) Brussels, Copenhagen, Madrid, Paris', icon: 'feather-sun' },
    { value: 'Kaliningrad, South Africa', label: '(GMT +2:00) Kaliningrad, South Africa', icon: 'feather-sun' },
    { value: 'Baghdad, Riyadh, Moscow, St. Petersburg', label: '(GMT +3:00) Baghdad, Riyadh, Moscow, St. Petersburg', icon: 'feather-sun' },
    { value: 'Tehran', label: '(GMT +3:30) Tehran', icon: 'feather-sun' },
    { value: 'Abu Dhabi, Muscat, Baku, Tbilisi', label: '(GMT +4:00) Abu Dhabi, Muscat, Baku, Tbilisi', icon: 'feather-sun' },
    { value: 'Kabul', label: '(GMT +4:30) Kabul', icon: 'feather-sun' },
    { value: 'Ekaterinburg, Islamabad, Karachi, Tashkent', label: '(GMT +5:00) Ekaterinburg, Islamabad, Karachi, Tashkent', icon: 'feather-sun' },
    { value: 'Bombay, Calcutta, Madras, New Delhi', label: '(GMT +5:30) Bombay, Calcutta, Madras, New Delhi', icon: 'feather-sun' },
    { value: 'Kathmandu, Pokhara', label: '(GMT +5:45) Kathmandu, Pokhara', icon: 'feather-sun' },
    { value: 'Almaty, Dhaka, Colombo', label: '(GMT +6:00) Almaty, Dhaka, Colombo', icon: 'feather-sun' },
    { value: 'Yangon, Mandalay', label: '(GMT +6:30) Yangon, Mandalay', icon: 'feather-sun' },
    { value: 'Bangkok, Hanoi, Jakarta', label: '(GMT +7:00) Bangkok, Hanoi, Jakarta', icon: 'feather-sun' },
    { value: 'Beijing, Perth, Singapore, Hong Kong', label: '(GMT +8:00) Beijing, Perth, Singapore, Hong Kong', icon: 'feather-sun' },
    { value: 'Eucla', label: '(GMT +8:45) Eucla', icon: 'feather-sun' },
    { value: 'Tokyo, Seoul, Osaka, Sapporo, Yakutsk', label: '(GMT +9:00) Tokyo, Seoul, Osaka, Sapporo, Yakutsk', icon: 'feather-sun' },
    { value: 'Adelaide, Darwin', label: '(GMT +9:30) Adelaide, Darwin', icon: 'feather-sun' },
    { value: 'Eastern Australia, Guam, Vladivostok', label: '(GMT +10:00) Eastern Australia, Guam, Vladivostok', icon: 'feather-sun' },
    { value: 'Lord Howe Island', label: '(GMT +10:30) Lord Howe Island', icon: 'feather-sun' },
    { value: 'Magadan, Solomon Islands, New Caledonia', label: '(GMT +11:00) Magadan, Solomon Islands, New Caledonia', icon: 'feather-sun' },
    { value: 'Norfolk Island', label: '(GMT +11:30) Norfolk Island', icon: 'feather-sun' },
    { value: 'Auckland, Wellington, Fiji, Kamchatka', label: '(GMT +12:00) Auckland, Wellington, Fiji, Kamchatka', icon: 'feather-sun' },
    { value: 'Chatham Islands', label: '(GMT +12:45) Chatham Islands', icon: 'feather-sun' },
    { value: 'Apia, Nukualofa', label: '(GMT +13:00) Apia, Nukualofa', icon: 'feather-sun' },
    { value: 'Line Islands, Tokelau', label: '(GMT +14:00) Line Islands, Tokelau', icon: 'feather-sun' }
  ];